/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: MiwhyMiwh (https://sketchfab.com/MiwhyMiwh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cosy-attic-room-7bcacdd698b14282bb88117cf29f58dd
Title: Cosy attic room
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    floor1_Floor_1_0: THREE.Mesh
    floor2_floor_2_0: THREE.Mesh
    wall2_wall_small_0: THREE.Mesh
    wall_roof_wall_small_0: THREE.Mesh
    wall_roof1_wall_invisible_visible_0: THREE.Mesh
    floor_round_floor_round_mat_0: THREE.Mesh
    wall_window_wall_edge_0: THREE.Mesh
    wall7_wall_invisible_visible_0: THREE.Mesh
    wall9_wall_top_0: THREE.Mesh
    fence1_Floor_1_0: THREE.Mesh
    fence_Floor_1_0: THREE.Mesh
    window1_glas_0: THREE.Mesh
    fence_stairs_Floor_1_0: THREE.Mesh
    ladder_ladder_mat_0: THREE.Mesh
    wall11_wall_edge_0: THREE.Mesh
    armchair_armchair_mat_0: THREE.Mesh
    bed_bed_mat_0: THREE.Mesh
    stove_stove_mat_0: THREE.Mesh
    Drawer2_bureau_mat2_0: THREE.Mesh
    Drawer1_bureau_mat2_0: THREE.Mesh
    Drawer_bureau_mat2_0: THREE.Mesh
    bureau_bureau_mat2_0: THREE.Mesh
    Shoerack_Shoe_rack_0: THREE.Mesh
    Cloth1Curtains_Curtain_mat_0: THREE.Mesh
    CurtainsRod_Curtain_mat_0: THREE.Mesh
    CurtainsCloth_Curtain_mat_0: THREE.Mesh
    Table_Table_mat_0: THREE.Mesh
    TableCloth_Table_mat_0: THREE.Mesh
    Chair_Chair_mat_0: THREE.Mesh
    Chair_rocking_Chair_rocking_mat_0: THREE.Mesh
    tree_tree_mat_0: THREE.Mesh
    Cloth_hanger1_Cloth_hanger_mat_0: THREE.Mesh
    Chair1_Chair_mat_0: THREE.Mesh
    Beauru_Beauru_mat_0: THREE.Mesh
    tree1_tree_mat_2_0: THREE.Mesh
    polySurface17_Clock_mat_0: THREE.Mesh
    Plant_1_Plant_mat_1_0: THREE.Mesh
    Plant_2_Plant_mat_2_0: THREE.Mesh
    bureau1_bureau_mat2_0: THREE.Mesh
    chest_chest_mat_0: THREE.Mesh
    Chest_2_Chest_mat_2_0: THREE.Mesh
    Desk_desk_mat_0: THREE.Mesh
    Plant_3_Plant_mat_1_0: THREE.Mesh
    Plant_4_Plant_mat_4_0: THREE.Mesh
    Plant_5_Plant_mat_4_0: THREE.Mesh
    Book_Book_mat_0: THREE.Mesh
    plant_hanging_plant_hanging_mat_0: THREE.Mesh
    Shelf1_Shelf_mat_0: THREE.Mesh
    bottle_1_bottles_mat_0: THREE.Mesh
    bottle_2_bottles_mat_0: THREE.Mesh
    bottle_3_bottles_mat_0: THREE.Mesh
    bottle_4_bottles_mat_0: THREE.Mesh
    bottle_5_bottles_mat_0: THREE.Mesh
    tree2_tree_mat_3_0: THREE.Mesh
    book_book_mat_B_0: THREE.Mesh
    book_2_book_mat_R_0: THREE.Mesh
    book_3_book_mat_B_0: THREE.Mesh
    book_4_Book_mat_2_0: THREE.Mesh
    book_5_book_mat_R_0: THREE.Mesh
    book_6_Book_mat_2_0: THREE.Mesh
    book_7_Book_mat_2_0: THREE.Mesh
    Box_wooden_box_wooden_0: THREE.Mesh
    bottle_6_bottles_mat_0: THREE.Mesh
    bottle_7_bottles_mat_0: THREE.Mesh
    book_8_book_mat_B_0: THREE.Mesh
    book_9_book_mat_R_0: THREE.Mesh
    book_10_Book_mat_2_0: THREE.Mesh
    book_11_Book_mat_2_0: THREE.Mesh
    book_12_book_mat_B_0: THREE.Mesh
    lamp_lamp_mat_0: THREE.Mesh
    Brush_Brush_mat_0: THREE.Mesh
    Candle_Candle_mat_0: THREE.Mesh
    candle_under_candle_under_mat_0: THREE.Mesh
    Beams_Beams_circle_mat_0: THREE.Mesh
    Globe_Globe_mat_0: THREE.Mesh
    Wood_7_Wood_mat_0: THREE.Mesh
    Wood_4_Wood_mat_0: THREE.Mesh
    Wood_3_Wood_mat_0: THREE.Mesh
    Wood_5_Wood_mat_0: THREE.Mesh
    Wood_6_Wood_mat_0: THREE.Mesh
    Wood_1_Wood_mat_0: THREE.Mesh
    Wood_2_Wood_mat_0: THREE.Mesh
    Pillow_pillow_mat_2_0: THREE.Mesh
    football_football_mat_0: THREE.Mesh
    Pillow1_pillow_mat_2_0: THREE.Mesh
    Pillow2_pillow_mat_0: THREE.Mesh
    Pillow3_pillow_mat_0: THREE.Mesh
    carpet_carpet__mat_0: THREE.Mesh
    table_tea_table_tea_mat_0: THREE.Mesh
    flags_textile_mat_0: THREE.Mesh
    flags1_textile_mat_0: THREE.Mesh
    Tower_wall_tower_0: THREE.Mesh
    glass_tower_glas_0: THREE.Mesh
    lamp1_lamp_mat_0: THREE.Mesh
    lamp2_lamp_mat_0: THREE.Mesh
    lamp3_lamp_mat_0: THREE.Mesh
    lamp4_lamp_mat_0: THREE.Mesh
    lamp5_lamp_mat_0: THREE.Mesh
    Mirror_mirror_0: THREE.Mesh
    window_border_wall_edge_0: THREE.Mesh
    glass2_glas_0: THREE.Mesh
    plant_hanging1_plant_hanging_mat_0: THREE.Mesh
    wall_smallside_wall_small_0: THREE.Mesh
    window_border1_window_border_mats_0: THREE.Mesh
    window_border2_window_border_mats_0: THREE.Mesh
    Shelf2_Shelf_mat_0: THREE.Mesh
    beam_beam_mat_0: THREE.Mesh
    window_glas_0: THREE.Mesh
    textile1_textile_mat_0: THREE.Mesh
    textile2_textile_mat_0: THREE.Mesh
    chair_desk_chair_desk_mat_0: THREE.Mesh
    bottle_8_bottles_mat_0: THREE.Mesh
    bottle_9_bottles_mat_0: THREE.Mesh
  }
  materials: {
    Floor_1: THREE.MeshStandardMaterial
    floor_2: THREE.MeshStandardMaterial
    wall_small: THREE.MeshStandardMaterial
    wall_invisible_visible: THREE.MeshStandardMaterial
    floor_round_mat: THREE.MeshStandardMaterial
    wall_edge: THREE.MeshStandardMaterial
    wall_top: THREE.MeshStandardMaterial
    glas: THREE.MeshStandardMaterial
    ladder_mat: THREE.MeshStandardMaterial
    armchair_mat: THREE.MeshStandardMaterial
    bed_mat: THREE.MeshStandardMaterial
    stove_mat: THREE.MeshStandardMaterial
    bureau_mat2: THREE.MeshStandardMaterial
    Shoe_rack: THREE.MeshStandardMaterial
    Curtain_mat: THREE.MeshStandardMaterial
    Table_mat: THREE.MeshStandardMaterial
    Chair_mat: THREE.MeshStandardMaterial
    Chair_rocking_mat: THREE.MeshStandardMaterial
    tree_mat: THREE.MeshStandardMaterial
    Cloth_hanger_mat: THREE.MeshStandardMaterial
    Beauru_mat: THREE.MeshStandardMaterial
    tree_mat_2: THREE.MeshStandardMaterial
    Clock_mat: THREE.MeshStandardMaterial
    Plant_mat_1: THREE.MeshStandardMaterial
    Plant_mat_2: THREE.MeshStandardMaterial
    chest_mat: THREE.MeshStandardMaterial
    Chest_mat_2: THREE.MeshStandardMaterial
    desk_mat: THREE.MeshStandardMaterial
    Plant_mat_4: THREE.MeshStandardMaterial
    Book_mat: THREE.MeshStandardMaterial
    plant_hanging_mat: THREE.MeshStandardMaterial
    Shelf_mat: THREE.MeshStandardMaterial
    bottles_mat: THREE.MeshStandardMaterial
    tree_mat_3: THREE.MeshStandardMaterial
    book_mat_B: THREE.MeshStandardMaterial
    book_mat_R: THREE.MeshStandardMaterial
    Book_mat_2: THREE.MeshStandardMaterial
    box_wooden: THREE.MeshStandardMaterial
    lamp_mat: THREE.MeshStandardMaterial
    Brush_mat: THREE.MeshStandardMaterial
    Candle_mat: THREE.MeshStandardMaterial
    candle_under_mat: THREE.MeshStandardMaterial
    Beams_circle_mat: THREE.MeshStandardMaterial
    Globe_mat: THREE.MeshStandardMaterial
    Wood_mat: THREE.MeshStandardMaterial
    pillow_mat_2: THREE.MeshStandardMaterial
    football_mat: THREE.MeshStandardMaterial
    pillow_mat: THREE.MeshStandardMaterial
    carpet__mat: THREE.MeshStandardMaterial
    table_tea_mat: THREE.MeshStandardMaterial
    textile_mat: THREE.MeshStandardMaterial
    wall_tower: THREE.MeshStandardMaterial
    mirror: THREE.MeshStandardMaterial
    window_border_mats: THREE.MeshStandardMaterial
    beam_mat: THREE.MeshStandardMaterial
    chair_desk_mat: THREE.MeshStandardMaterial
  }
}

export function Attic(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/attic/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={16.327}>
          <group
            name="b3e1074aea8e4147807e076c649b06e0fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}>
            <group name="RootNode">
              <group name="floor1">
                <mesh
                  name="floor1_Floor_1_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.floor1_Floor_1_0.geometry}
                  material={materials.Floor_1}
                />
              </group>
              <group name="floor2" position={[0.358, -0.149, -0.062]}>
                <mesh
                  name="floor2_floor_2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.floor2_floor_2_0.geometry}
                  material={materials.floor_2}
                />
              </group>
              <group name="wall2">
                <mesh
                  name="wall2_wall_small_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.wall2_wall_small_0.geometry}
                  material={materials.wall_small}
                />
              </group>
              <group name="wall_roof">
                <mesh
                  name="wall_roof_wall_small_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.wall_roof_wall_small_0.geometry}
                  material={materials.wall_small}
                />
              </group>
              <group name="wall_roof1">
                <mesh
                  name="wall_roof1_wall_invisible_visible_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.wall_roof1_wall_invisible_visible_0.geometry}
                  material={materials.wall_invisible_visible}
                />
              </group>
              <group name="floor_round">
                <mesh
                  name="floor_round_floor_round_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.floor_round_floor_round_mat_0.geometry}
                  material={materials.floor_round_mat}
                />
              </group>
              <group name="wall_window">
                <mesh
                  name="wall_window_wall_edge_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.wall_window_wall_edge_0.geometry}
                  material={materials.wall_edge}
                />
              </group>
              <group name="wall7" position={[0, -0.612, -0.123]}>
                <mesh
                  name="wall7_wall_invisible_visible_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.wall7_wall_invisible_visible_0.geometry}
                  material={materials.wall_invisible_visible}
                />
              </group>
              <group name="wall9">
                <mesh
                  name="wall9_wall_top_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.wall9_wall_top_0.geometry}
                  material={materials.wall_top}
                />
              </group>
              <group name="fence1">
                <mesh
                  name="fence1_Floor_1_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.fence1_Floor_1_0.geometry}
                  material={materials.Floor_1}
                />
              </group>
              <group name="fence">
                <mesh
                  name="fence_Floor_1_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.fence_Floor_1_0.geometry}
                  material={materials.Floor_1}
                />
              </group>
              <group name="window1">
                <mesh
                  name="window1_glas_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.window1_glas_0.geometry}
                  material={materials.glas}
                />
              </group>
              <group name="fence_stairs">
                <mesh
                  name="fence_stairs_Floor_1_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.fence_stairs_Floor_1_0.geometry}
                  material={materials.Floor_1}
                />
              </group>
              <group name="ladder">
                <mesh
                  name="ladder_ladder_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.ladder_ladder_mat_0.geometry}
                  material={materials.ladder_mat}
                />
              </group>
              <group name="wall11">
                <mesh
                  name="wall11_wall_edge_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.wall11_wall_edge_0.geometry}
                  material={materials.wall_edge}
                />
              </group>
              <group name="armchair" position={[1.265, -0.035, 0.53]}>
                <mesh
                  name="armchair_armchair_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.armchair_armchair_mat_0.geometry}
                  material={materials.armchair_mat}
                />
              </group>
              <group name="bed" position={[2.28, -0.037, -3.944]}>
                <mesh
                  name="bed_bed_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.bed_bed_mat_0.geometry}
                  material={materials.bed_mat}
                />
              </group>
              <group name="stove">
                <mesh
                  name="stove_stove_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.stove_stove_mat_0.geometry}
                  material={materials.stove_mat}
                />
              </group>
              <group name="Drawer_all">
                <group name="Drawer2">
                  <mesh
                    name="Drawer2_bureau_mat2_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Drawer2_bureau_mat2_0.geometry}
                    material={materials.bureau_mat2}
                  />
                </group>
                <group name="Drawer1">
                  <mesh
                    name="Drawer1_bureau_mat2_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Drawer1_bureau_mat2_0.geometry}
                    material={materials.bureau_mat2}
                  />
                </group>
                <group name="Drawer">
                  <mesh
                    name="Drawer_bureau_mat2_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Drawer_bureau_mat2_0.geometry}
                    material={materials.bureau_mat2}
                  />
                </group>
                <group name="bureau">
                  <mesh
                    name="bureau_bureau_mat2_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.bureau_bureau_mat2_0.geometry}
                    material={materials.bureau_mat2}
                  />
                </group>
              </group>
              <group name="Shoerack">
                <mesh
                  name="Shoerack_Shoe_rack_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Shoerack_Shoe_rack_0.geometry}
                  material={materials.Shoe_rack}
                />
              </group>
              <group name="Curtians">
                <group name="Cloth1Curtains">
                  <mesh
                    name="Cloth1Curtains_Curtain_mat_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cloth1Curtains_Curtain_mat_0.geometry}
                    material={materials.Curtain_mat}
                  />
                </group>
                <group name="CurtainsRod">
                  <mesh
                    name="CurtainsRod_Curtain_mat_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.CurtainsRod_Curtain_mat_0.geometry}
                    material={materials.Curtain_mat}
                  />
                </group>
                <group name="CurtainsCloth">
                  <mesh
                    name="CurtainsCloth_Curtain_mat_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.CurtainsCloth_Curtain_mat_0.geometry}
                    material={materials.Curtain_mat}
                  />
                </group>
              </group>
              <group name="Table">
                <group name="Table_1">
                  <mesh
                    name="Table_Table_mat_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Table_Table_mat_0.geometry}
                    material={materials.Table_mat}
                  />
                </group>
                <group name="TableCloth">
                  <mesh
                    name="TableCloth_Table_mat_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.TableCloth_Table_mat_0.geometry}
                    material={materials.Table_mat}
                  />
                </group>
              </group>
              <group name="Chair">
                <mesh
                  name="Chair_Chair_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Chair_Chair_mat_0.geometry}
                  material={materials.Chair_mat}
                />
              </group>
              <group name="Chair_rocking">
                <mesh
                  name="Chair_rocking_Chair_rocking_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Chair_rocking_Chair_rocking_mat_0.geometry}
                  material={materials.Chair_rocking_mat}
                />
              </group>
              <group
                name="tree"
                position={[-0.247, -2.437, 11.637]}
                rotation={[0.007, -0.006, 0.046]}>
                <mesh
                  name="tree_tree_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.tree_tree_mat_0.geometry}
                  material={materials.tree_mat}
                />
              </group>
              <group name="Cloth_hanger1">
                <mesh
                  name="Cloth_hanger1_Cloth_hanger_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Cloth_hanger1_Cloth_hanger_mat_0.geometry}
                  material={materials.Cloth_hanger_mat}
                />
              </group>
              <group name="Chair1" position={[-5.598, 0, 6.792]}>
                <mesh
                  name="Chair1_Chair_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Chair1_Chair_mat_0.geometry}
                  material={materials.Chair_mat}
                />
              </group>
              <group name="Beauru" position={[40.048, 8.329, -24.232]} scale={3.849}>
                <mesh
                  name="Beauru_Beauru_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Beauru_Beauru_mat_0.geometry}
                  material={materials.Beauru_mat}
                />
              </group>
              <group name="tree1" position={[-9.16, -0.534, 11.985]}>
                <mesh
                  name="tree1_tree_mat_2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.tree1_tree_mat_2_0.geometry}
                  material={materials.tree_mat_2}
                />
              </group>
              <group name="polySurface17" position={[0.742, 0, 0]}>
                <mesh
                  name="polySurface17_Clock_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.polySurface17_Clock_mat_0.geometry}
                  material={materials.Clock_mat}
                />
              </group>
              <group name="Plant_1">
                <mesh
                  name="Plant_1_Plant_mat_1_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Plant_1_Plant_mat_1_0.geometry}
                  material={materials.Plant_mat_1}
                />
              </group>
              <group name="Plant_2">
                <mesh
                  name="Plant_2_Plant_mat_2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Plant_2_Plant_mat_2_0.geometry}
                  material={materials.Plant_mat_2}
                />
              </group>
              <group name="bureau1" position={[-37.802, -5.085, 23.234]}>
                <mesh
                  name="bureau1_bureau_mat2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.bureau1_bureau_mat2_0.geometry}
                  material={materials.bureau_mat2}
                />
              </group>
              <group name="chest">
                <mesh
                  name="chest_chest_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.chest_chest_mat_0.geometry}
                  material={materials.chest_mat}
                />
              </group>
              <group name="Chest_2" position={[-6.292, 0.001, 0.42]} scale={[1, 1, 0.825]}>
                <mesh
                  name="Chest_2_Chest_mat_2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Chest_2_Chest_mat_2_0.geometry}
                  material={materials.Chest_mat_2}
                />
              </group>
              <group name="Desk" position={[-22.638, 3.64, 7.231]} scale={[4.976, 4.382, 9.662]}>
                <mesh
                  name="Desk_desk_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Desk_desk_mat_0.geometry}
                  material={materials.desk_mat}
                />
              </group>
              <group name="Plant_3" position={[-38.626, -5.54, 53.377]} scale={0.891}>
                <mesh
                  name="Plant_3_Plant_mat_1_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Plant_3_Plant_mat_1_0.geometry}
                  material={materials.Plant_mat_1}
                />
              </group>
              <group name="Plant_4" position={[0, -0.067, 0]}>
                <mesh
                  name="Plant_4_Plant_mat_4_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Plant_4_Plant_mat_4_0.geometry}
                  material={materials.Plant_mat_4}
                />
              </group>
              <group
                name="Plant_5"
                position={[52.818, 0, -90.527]}
                rotation={[-Math.PI, -0.508, -Math.PI]}>
                <mesh
                  name="Plant_5_Plant_mat_4_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Plant_5_Plant_mat_4_0.geometry}
                  material={materials.Plant_mat_4}
                />
              </group>
              <group name="Book" position={[-21.544, -10.98, -40.992]} scale={0.837}>
                <mesh
                  name="Book_Book_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Book_Book_mat_0.geometry}
                  material={materials.Book_mat}
                />
              </group>
              <group name="plant_hanging" position={[0, 1.717, 12.927]}>
                <mesh
                  name="plant_hanging_plant_hanging_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.plant_hanging_plant_hanging_mat_0.geometry}
                  material={materials.plant_hanging_mat}
                />
              </group>
              <group
                name="Shelf1"
                position={[39.085, 19.726, -34.779]}
                scale={[2.151, 0.668, 16.376]}>
                <mesh
                  name="Shelf1_Shelf_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Shelf1_Shelf_mat_0.geometry}
                  material={materials.Shelf_mat}
                />
              </group>
              <group name="bottle_1" position={[38.679, 20.593, -29.044]} scale={0.52}>
                <mesh
                  name="bottle_1_bottles_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.bottle_1_bottles_mat_0.geometry}
                  material={materials.bottles_mat}
                />
              </group>
              <group name="bottle_2" position={[40.014, 15.316, -29.044]} scale={0.52}>
                <mesh
                  name="bottle_2_bottles_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.bottle_2_bottles_mat_0.geometry}
                  material={materials.bottles_mat}
                />
              </group>
              <group name="bottle_3" position={[39.871, 15.224, -38.253]} scale={0.52}>
                <mesh
                  name="bottle_3_bottles_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.bottle_3_bottles_mat_0.geometry}
                  material={materials.bottles_mat}
                />
              </group>
              <group name="bottle_4" position={[39.924, 15.499, -31.27]} scale={0.805}>
                <mesh
                  name="bottle_4_bottles_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.bottle_4_bottles_mat_0.geometry}
                  material={materials.bottles_mat}
                />
              </group>
              <group name="bottle_5" position={[38.626, 20.518, -40.465]} scale={0.4}>
                <mesh
                  name="bottle_5_bottles_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.bottle_5_bottles_mat_0.geometry}
                  material={materials.bottles_mat}
                />
              </group>
              <group name="tree2" position={[0.716, 8.24, -14.117]} scale={0.274}>
                <mesh
                  name="tree2_tree_mat_3_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.tree2_tree_mat_3_0.geometry}
                  material={materials.tree_mat_3}
                />
              </group>
              <group name="book" position={[39.962, 15.722, -32.588]} scale={[1.029, 0.375, 1.975]}>
                <mesh
                  name="book_book_mat_B_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.book_book_mat_B_0.geometry}
                  material={materials.book_mat_B}
                />
              </group>
              <group
                name="book_2"
                position={[39.897, 15.717, -33.252]}
                scale={[1.029, 0.375, 1.975]}>
                <mesh
                  name="book_2_book_mat_R_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.book_2_book_mat_R_0.geometry}
                  material={materials.book_mat_R}
                />
              </group>
              <group
                name="book_3"
                position={[39.897, 15.74, -33.738]}
                scale={[1.029, 0.375, 1.975]}>
                <mesh
                  name="book_3_book_mat_B_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.book_3_book_mat_B_0.geometry}
                  material={materials.book_mat_B}
                />
              </group>
              <group
                name="book_4"
                position={[39.897, 15.761, -34.182]}
                scale={[1.029, 0.375, 1.975]}>
                <mesh
                  name="book_4_Book_mat_2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.book_4_Book_mat_2_0.geometry}
                  material={materials.Book_mat_2}
                />
              </group>
              <group
                name="book_5"
                position={[39.897, 15.711, -34.696]}
                scale={[1.029, 0.375, 1.975]}>
                <mesh
                  name="book_5_book_mat_R_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.book_5_book_mat_R_0.geometry}
                  material={materials.book_mat_R}
                />
              </group>
              <group
                name="book_6"
                position={[39.897, 16.061, -35.355]}
                scale={[1.029, 0.375, 1.975]}>
                <mesh
                  name="book_6_Book_mat_2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.book_6_Book_mat_2_0.geometry}
                  material={materials.Book_mat_2}
                />
              </group>
              <group
                name="book_7"
                position={[40.874, 16.528, -37.374]}
                scale={[1.029, 0.375, 1.975]}>
                <mesh
                  name="book_7_Book_mat_2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.book_7_Book_mat_2_0.geometry}
                  material={materials.Book_mat_2}
                />
              </group>
              <group
                name="Box_wooden"
                position={[40.341, 6.733, -33.394]}
                scale={[2.712, 1.266, 3.578]}>
                <mesh
                  name="Box_wooden_box_wooden_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Box_wooden_box_wooden_0.geometry}
                  material={materials.box_wooden}
                />
              </group>
              <group name="bottle_6" position={[40.921, 6.814, -32.247]} scale={0.4}>
                <mesh
                  name="bottle_6_bottles_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.bottle_6_bottles_mat_0.geometry}
                  material={materials.bottles_mat}
                />
              </group>
              <group name="bottle_7" position={[40.921, 6.785, -33.468]} scale={0.4}>
                <mesh
                  name="bottle_7_bottles_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.bottle_7_bottles_mat_0.geometry}
                  material={materials.bottles_mat}
                />
              </group>
              <group
                name="book_8"
                position={[39.897, 7.376, -34.128]}
                scale={[1.029, 0.375, 1.975]}>
                <mesh
                  name="book_8_book_mat_B_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.book_8_book_mat_B_0.geometry}
                  material={materials.book_mat_B}
                />
              </group>
              <group
                name="book_9"
                position={[39.897, 7.332, -32.777]}
                scale={[1.029, 0.375, 1.975]}>
                <mesh
                  name="book_9_book_mat_R_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.book_9_book_mat_R_0.geometry}
                  material={materials.book_mat_R}
                />
              </group>
              <group
                name="book_10"
                position={[39.725, 7.355, -33.683]}
                scale={[1.262, 0.375, 1.975]}>
                <mesh
                  name="book_10_Book_mat_2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.book_10_Book_mat_2_0.geometry}
                  material={materials.Book_mat_2}
                />
              </group>
              <group
                name="book_11"
                position={[39.745, 21.85, -35.196]}
                scale={[1.029, 0.375, 1.975]}>
                <mesh
                  name="book_11_Book_mat_2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.book_11_Book_mat_2_0.geometry}
                  material={materials.Book_mat_2}
                />
              </group>
              <group
                name="book_12"
                position={[38.768, 21.338, -33.177]}
                scale={[1.029, 0.375, 1.975]}>
                <mesh
                  name="book_12_book_mat_B_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.book_12_book_mat_B_0.geometry}
                  material={materials.book_mat_B}
                />
              </group>
              <group name="lamp" position={[38.74, 20.873, -31.304]} scale={1.027}>
                <mesh
                  name="lamp_lamp_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.lamp_lamp_mat_0.geometry}
                  material={materials.lamp_mat}
                />
              </group>
              <group name="Brush" position={[-20.137, 6.202, 9.523]} scale={0.123}>
                <mesh
                  name="Brush_Brush_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Brush_Brush_mat_0.geometry}
                  material={materials.Brush_mat}
                />
              </group>
              <group name="Candle" position={[18.319, 6.873, 12.987]} scale={0.136}>
                <mesh
                  name="Candle_Candle_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Candle_Candle_mat_0.geometry}
                  material={materials.Candle_mat}
                />
              </group>
              <group
                name="candle_under"
                position={[18.379, 5.865, 13.01]}
                scale={[0.812, 0.379, 1.072]}>
                <mesh
                  name="candle_under_candle_under_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.candle_under_candle_under_mat_0.geometry}
                  material={materials.candle_under_mat}
                />
              </group>
              <group name="Beams">
                <mesh
                  name="Beams_Beams_circle_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Beams_Beams_circle_mat_0.geometry}
                  material={materials.Beams_circle_mat}
                />
              </group>
              <group name="Globe" position={[1.028, 0.045, -2.678]}>
                <mesh
                  name="Globe_Globe_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Globe_Globe_mat_0.geometry}
                  material={materials.Globe_mat}
                />
              </group>
              <group name="Wood" position={[0.541, -0.374, -0.398]} scale={0.794}>
                <group name="Wood_7" position={[-13.929, 2.24, -1.983]}>
                  <mesh
                    name="Wood_7_Wood_mat_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Wood_7_Wood_mat_0.geometry}
                    material={materials.Wood_mat}
                  />
                </group>
                <group name="Wood_4" position={[-11.908, 3.145, -0.916]}>
                  <mesh
                    name="Wood_4_Wood_mat_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Wood_4_Wood_mat_0.geometry}
                    material={materials.Wood_mat}
                  />
                </group>
                <group name="Wood_3" position={[-12.737, 2.142, -0.651]}>
                  <mesh
                    name="Wood_3_Wood_mat_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Wood_3_Wood_mat_0.geometry}
                    material={materials.Wood_mat}
                  />
                </group>
                <group name="Wood_5" position={[-10.475, 3.145, -1.194]}>
                  <mesh
                    name="Wood_5_Wood_mat_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Wood_5_Wood_mat_0.geometry}
                    material={materials.Wood_mat}
                  />
                </group>
                <group name="Wood_6" position={[-11.206, 4.125, -0.916]}>
                  <mesh
                    name="Wood_6_Wood_mat_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Wood_6_Wood_mat_0.geometry}
                    material={materials.Wood_mat}
                  />
                </group>
                <group name="Wood_1" position={[-9.925, 2.142, -0.916]}>
                  <mesh
                    name="Wood_1_Wood_mat_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Wood_1_Wood_mat_0.geometry}
                    material={materials.Wood_mat}
                  />
                </group>
                <group name="Wood_2" position={[-11.376, 2.142, -0.916]}>
                  <mesh
                    name="Wood_2_Wood_mat_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Wood_2_Wood_mat_0.geometry}
                    material={materials.Wood_mat}
                  />
                </group>
              </group>
              <group name="Pillow" position={[-5.982, 11.483, -29.961]} scale={4.989}>
                <mesh
                  name="Pillow_pillow_mat_2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Pillow_pillow_mat_2_0.geometry}
                  material={materials.pillow_mat_2}
                />
              </group>
              <group name="football" position={[38.379, 6.944, -27.811]} scale={2.006}>
                <mesh
                  name="football_football_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.football_football_mat_0.geometry}
                  material={materials.football_mat}
                />
              </group>
              <group name="Pillow1" position={[-13.234, 11.011, -26.404]} scale={3.6}>
                <mesh
                  name="Pillow1_pillow_mat_2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Pillow1_pillow_mat_2_0.geometry}
                  material={materials.pillow_mat_2}
                />
              </group>
              <group name="Pillow2" position={[-12.802, 11.647, -31.113]} scale={4.151}>
                <mesh
                  name="Pillow2_pillow_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Pillow2_pillow_mat_0.geometry}
                  material={materials.pillow_mat}
                />
              </group>
              <group name="Pillow3" position={[-12.145, 10.953, -21.926]} scale={3.113}>
                <mesh
                  name="Pillow3_pillow_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Pillow3_pillow_mat_0.geometry}
                  material={materials.pillow_mat}
                />
              </group>
              <group name="carpet" position={[-7.585, 10.593, -25.383]} scale={9.424}>
                <mesh
                  name="carpet_carpet__mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.carpet_carpet__mat_0.geometry}
                  material={materials.carpet__mat}
                />
              </group>
              <group name="table_tea">
                <mesh
                  name="table_tea_table_tea_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.table_tea_table_tea_mat_0.geometry}
                  material={materials.table_tea_mat}
                />
              </group>
              <group name="flags">
                <mesh
                  name="flags_textile_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.flags_textile_mat_0.geometry}
                  material={materials.textile_mat}
                />
              </group>
              <group name="flags1" position={[-4.47, -5.883, -0.269]} scale={0.885}>
                <mesh
                  name="flags1_textile_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.flags1_textile_mat_0.geometry}
                  material={materials.textile_mat}
                />
              </group>
              <group name="Tower">
                <mesh
                  name="Tower_wall_tower_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Tower_wall_tower_0.geometry}
                  material={materials.wall_tower}
                />
              </group>
              <group name="glass_tower" position={[-9.125, -0.022, 6.54]} scale={[1.134, 1.077, 1]}>
                <mesh
                  name="glass_tower_glas_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.glass_tower_glas_0.geometry}
                  material={materials.glas}
                />
              </group>
              <group
                name="lamp1"
                position={[-7.062, 13.547, -22.469]}
                rotation={[-0.187, 0, -0.381]}
                scale={1.027}>
                <mesh
                  name="lamp1_lamp_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.lamp1_lamp_mat_0.geometry}
                  material={materials.lamp_mat}
                />
              </group>
              <group name="lamp2" position={[-7.03, 11.453, -8.759]} scale={1.027}>
                <mesh
                  name="lamp2_lamp_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.lamp2_lamp_mat_0.geometry}
                  material={materials.lamp_mat}
                />
              </group>
              <group name="lamp3" position={[-12.059, 11.31, -11.86]} scale={1.027}>
                <mesh
                  name="lamp3_lamp_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.lamp3_lamp_mat_0.geometry}
                  material={materials.lamp_mat}
                />
              </group>
              <group name="lamp4" position={[-5.711, 3.791, 16.151]} scale={1.027}>
                <mesh
                  name="lamp4_lamp_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.lamp4_lamp_mat_0.geometry}
                  material={materials.lamp_mat}
                />
              </group>
              <group name="lamp5" position={[-23.551, 7.628, -0.625]} scale={1.027}>
                <mesh
                  name="lamp5_lamp_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.lamp5_lamp_mat_0.geometry}
                  material={materials.lamp_mat}
                />
              </group>
              <group name="Mirror">
                <mesh
                  name="Mirror_mirror_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Mirror_mirror_0.geometry}
                  material={materials.mirror}
                />
              </group>
              <group name="window_border">
                <mesh
                  name="window_border_wall_edge_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.window_border_wall_edge_0.geometry}
                  material={materials.wall_edge}
                />
              </group>
              <group name="glass2">
                <mesh
                  name="glass2_glas_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.glass2_glas_0.geometry}
                  material={materials.glas}
                />
              </group>
              <group name="plant_hanging1" position={[-35.365, 2.916, 30.234]}>
                <mesh
                  name="plant_hanging1_plant_hanging_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.plant_hanging1_plant_hanging_mat_0.geometry}
                  material={materials.plant_hanging_mat}
                />
              </group>
              <group name="wall_smallside">
                <mesh
                  name="wall_smallside_wall_small_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.wall_smallside_wall_small_0.geometry}
                  material={materials.wall_small}
                />
              </group>
              <group name="window_border1">
                <mesh
                  name="window_border1_window_border_mats_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.window_border1_window_border_mats_0.geometry}
                  material={materials.window_border_mats}
                />
              </group>
              <group name="window_border2">
                <mesh
                  name="window_border2_window_border_mats_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.window_border2_window_border_mats_0.geometry}
                  material={materials.window_border_mats}
                />
              </group>
              <group
                name="Shelf2"
                position={[40.141, 14.372, -34.781]}
                rotation={[0, 0.011, 0]}
                scale={[2.151, 0.668, 16.376]}>
                <mesh
                  name="Shelf2_Shelf_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Shelf2_Shelf_mat_0.geometry}
                  material={materials.Shelf_mat}
                />
              </group>
              <group
                name="beam"
                position={[28.041, 28.442, -37.154]}
                scale={[21.537, 1.555, 1.555]}>
                <mesh
                  name="beam_beam_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.beam_beam_mat_0.geometry}
                  material={materials.beam_mat}
                />
              </group>
              <group name="window">
                <mesh
                  name="window_glas_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.window_glas_0.geometry}
                  material={materials.glas}
                />
              </group>
              <group name="textile1" position={[-0.4, -0.137, 0]}>
                <mesh
                  name="textile1_textile_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.textile1_textile_mat_0.geometry}
                  material={materials.textile_mat}
                />
              </group>
              <group name="textile2" position={[-4.014, 0.086, -0.768]} scale={0.922}>
                <mesh
                  name="textile2_textile_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.textile2_textile_mat_0.geometry}
                  material={materials.textile_mat}
                />
              </group>
              <group name="chair_desk">
                <mesh
                  name="chair_desk_chair_desk_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.chair_desk_chair_desk_mat_0.geometry}
                  material={materials.chair_desk_mat}
                />
              </group>
              <group name="bottle_8" position={[39.871, 15.224, -38.253]} scale={0.52}>
                <mesh
                  name="bottle_8_bottles_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.bottle_8_bottles_mat_0.geometry}
                  material={materials.bottles_mat}
                />
              </group>
              <group name="bottle_9" position={[40.287, 15.109, -40.534]} scale={0.4}>
                <mesh
                  name="bottle_9_bottles_mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.bottle_9_bottles_mat_0.geometry}
                  material={materials.bottles_mat}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/attic/scene.gltf')
